#ifndef PAP_COMMON_GAME_DEFINE_H_
#define PAP_COMMON_GAME_DEFINE_H_

#define INVALID_COUNTRY -1
#define INVALID_JOB -1
#define INVALID_SEX -1
#define INVALID_GUILD_ID -1
#define INVALID_RESOURCE -1
#define INVALID_RULERID -1
#define INVALID_PRICE 0
#define INVALID_ITEM_ID 0
#define INVALID_ITEM_POS -1
#define INVALID_TIME 0xFFFFFFFF
#define INVALID_PAI_TYPE 0
#define INVALID_SOUL_TYPE 0
#define BASE_BAG_POS 185
#define MAX_GUILD_LEVEL 5 //公会最大等级

#endif //PAP_COMMON_GAME_DEFINE_H_
