#!/bin/sh

find . -name "*.php" -o -name "*.lua" -o -name "*.h" -o -name "*.cpp" -o -name "*.c" -o -name "*.cc" -o -name "*.hpp" > cscope.files
find ../common -name "*.php" -o -name "*.lua" -o -name "*.h" -o -name "*.cpp" -o -name "*.c" -o -name "*.cc" -o -name "*.hpp" >> cscope.files
find ../../include/common -name "*.php" -o -name "*.lua" -o -name "*.h" -o -name "*.cpp" -o -name "*.c" -o -name "*.cc" -o -name "*.hpp" >> cscope.files
find ../../include/server -name "*.php" -o -name "*.lua" -o -name "*.h" -o -name "*.cpp" -o -name "*.c" -o -name "*.cc" -o -name "*.hpp" >> cscope.files
cscope -bkq -i cscope.files
ctags -R
