#include "CEGUIWindowManager.h"
#include "CEGUIWindow.h"
#include "CEGUIUDim.h"
#include "elements/CEGUIProgressBar.h"
#include "CEGUIAnimateManager.h"
#include "FalagardAnimate.h"
#include "elements/CEGUIStaticImage.h"
#include "CEGUIPropertyHelper.h"
#include "CEGUIColourRect.h"
#include "elements/CEGUIPushButton.h"
#include "CEGUIPropertyHelper.h"
#include "FalagardSelfFitWindow.h"
#include "IFalagardSelfFitWindow.h"
#include "FalButton.h"

#include "vengine/db/system.h"
#include "vengine/db/struct/all.h"
#include "vgui/window/manager.h"
#include "vgui/creature/head/board/behit.h"
#include "vgui/creature/head/board/behit_manager.h"
#include "vgui/creature/head/board/system.h"

#include "vgui/creature/head/board/base.h"
